KonohagoWebApp/KonohagoWebApp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KonohagoWebApp.Helpers;
using KonohagoWebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;
using KonohagoWebApp.Repository.Interfaces;
namespace KonohagoWebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> OnGet()
        {
            if (HttpContext.Request.Query["handler"] == "ClearSession")
            { 
                return OnPostClearSession();
            }
            if (HttpContext.Request.Cookies.ContainsKey("email") && HttpContext.Request.Cookies.ContainsKey("password") && HttpContext.Session.GetString("role")=="Guest")
            {
                var repository = HttpContext.RequestServices.GetService<IUserRepository>();
                var email = HttpContext.Request.Cookies["email"];
                var password = HttpContext.Request.Cookies["password"];
                var user = await repository.GetUserByEmailAndPasswordAsync(email, password);
                var a = HttpContext.Session.GetString("role");
                HttpContext.Session.Set<User>("Current_user", user);
            }
            if (HttpContext.Session.GetString("role") == "Guest")
            {
                ViewData["name"] = "Путник";
                ViewData["role"] = "Guest";
                return null;
            }
            else if (HttpContext.Session.GetString("role") == "User")
            {
                var user = HttpContext.Session.Get<User>("Current_user");
                ViewData["name"] = user.Nickname;
                ViewData["role"] = "User";
                return null;
            }
            return null;
        }
        public IActionResult OnPostClearSession()
        {
            HttpContext.Session.Clear();
            if (HttpContext.Request.Cookies["email"] != null || HttpContext.Request.Cookies["password"]!= null)
            {
                HttpContext.Response.Cookies.Delete("email");
                HttpContext.Response.Cookies.Delete("password");
            }

            return Redirect("/Index");
        }
    }
}

KonohagoWebApp/KonohagoWebApp/Pages/Shared/_ForeignStyle.cshtml
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">

KonohagoWebApp/KonohagoWebApp/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Models
@using KonohagoWebApp.Helpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KonohagoWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/mainPage.css" type="text/css" />
    @await Html.PartialAsync("_ForeignStyle")
   
</head>
<body>
    <header class="header-main-area">
        <div class="header-padding">
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-dark bg-black">
                    <a class="navbar-brand" href="#">Konohago</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="wide_navbar nav-item">
                                <a class="nav-link" asp-area="" asp-page="/Index">Главная</a>
                            </li>
                            <li class="wide_navbar nav-item">
                                <a class="nav-link" asp-area="" asp-page="/TitlesPage">Каталог аниме</a>
                            </li>
                            <li class="wide_navbar nav-item">
                                <a class="nav-link" asp-area="" asp-page="/FAQ">FAQ</a>
                            </li>
                            <li class="wide_navbar nav-item">
                                <a class="nav-link" asp-area="" asp-page="/Search">Поиск</a>
                            </li>
                            @if (Context.Session.GetString("role") == "Guest")
                            {
                                <li class="wide_navbar nav-item">
                                    <a class="nav-link" asp-area="" asp-page="/Registration">Регистрация</a>
                                </li>
                            }
                            @if (Context.Session.GetString("role") == "User")
                            {
                                <li class="wide_navbar nav-item">

                                    <a type="submit" class="nav-link" asp-page="Index" asp-page-handler="ClearSession">Выход</a>

                                </li>
                            }
                            @if (Context.Session.GetString("role") == "User")
                            {
                                <li class="wide_navbar nav-item">
                                    <a class="nav-link" href="/Profile/?id=@(Context.Session.Get<User>("Current_user").Id)">Мой профиль</a>
                                </li>
                            }
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @if (!Context.Request.Query.ContainsKey("id"))
    {
        <section class="about-area">
            <div class="about-padding">
                <div class="container">
                    <div class="about-title all-title">
                        <h2>О нас</h2>
                    </div>
                    <div class="row">
                        <div class="col-sm-5">
                            <div class="about-left">
                                <img class="img-fluid" src="/img/alesya_kal.png" alt="">
                            </div>
                        </div>
                        <div class="col-sm-7">
                            <div class="about-right-content">
                                <h3></h3>
                                <p class="olesya-kal">Группа молодых разработчиков, которые готовы идти вперед, не останавливаясь в развитии. Мы разрабатываем приложения, которыми можем гордиться </p>
                                <a asp-page="/DonatePage" id="btn_support" class="about-right-btn">Поддержать нас</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    }
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>

KonohagoWebApp/KonohagoWebApp/Pages/Shared/_StudiosList.cshtml
@using KonohagoWebApp.Models;
@model List<Studios>
@{ 
    var users = Model;
}
@foreach (var MyUser in Model)
{
    <div class="timeline-header">
        <div class="username">
            <h2 class="u-text u-text-1">@MyUser.Name, @MyUser.Foundation_date</h2>
        </div>
    </div>
}